// <auto-generated />
using System;
using BaseConn.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseConn.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseConn.Domain.models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ServiceId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BaseConn.Domain.models.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoteCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NoteCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("note_file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("note_file_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("note_file_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("note_file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("note_file_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteId");

                    b.HasIndex("UserId");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("BaseConn.Domain.models.NoteFile", b =>
                {
                    b.Property<Guid>("NoteFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoteFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NoteFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("NoteFileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NoteFileId");

                    b.HasIndex("NoteId");

                    b.ToTable("noteFiles");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Problem", b =>
                {
                    b.Property<Guid>("problem_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProblemStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("problem_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("problem_id");

                    b.HasIndex("FounderId");

                    b.HasIndex("UserId");

                    b.ToTable("problems");
                });

            modelBuilder.Entity("BaseConn.Domain.models.ProblemFile", b =>
                {
                    b.Property<Guid>("ProblemFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProblemFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProblemFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ProblemFileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProblemFileId");

                    b.HasIndex("ProblemId");

                    b.ToTable("problemFiles");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceSecondaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("services");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Solution", b =>
                {
                    b.Property<Guid>("solution_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SolutionRating")
                        .HasColumnType("float");

                    b.Property<Guid>("problem_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("solution_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("solution_file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("solution_file_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("solution_file_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("solution_file_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("solution_file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("solution_file_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("solution_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("solution_id");

                    b.HasIndex("problem_id");

                    b.ToTable("solutions");
                });

            modelBuilder.Entity("BaseConn.Domain.models.SolutionFile", b =>
                {
                    b.Property<Guid>("SolutionFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SolutionFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SolutionFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("SolutionFileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SolutionFileId");

                    b.HasIndex("SolutionId");

                    b.ToTable("solutionFiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BaseConn.Domain.models.ApplicationUser", b =>
                {
                    b.HasOne("BaseConn.Domain.models.Service", "service")
                        .WithMany("Users")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("service");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Note", b =>
                {
                    b.HasOne("BaseConn.Domain.models.ApplicationUser", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseConn.Domain.models.NoteFile", b =>
                {
                    b.HasOne("BaseConn.Domain.models.Note", "note")
                        .WithMany("NoteFiles")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("note");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Problem", b =>
                {
                    b.HasOne("BaseConn.Domain.models.ApplicationUser", "FounderUser")
                        .WithMany("FounderProblems")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BaseConn.Domain.models.ApplicationUser", "User")
                        .WithMany("Problems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FounderUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseConn.Domain.models.ProblemFile", b =>
                {
                    b.HasOne("BaseConn.Domain.models.Problem", "problem")
                        .WithMany("ProblemFiles")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("problem");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Solution", b =>
                {
                    b.HasOne("BaseConn.Domain.models.Problem", null)
                        .WithMany("solutions")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseConn.Domain.models.SolutionFile", b =>
                {
                    b.HasOne("BaseConn.Domain.models.Solution", "solution")
                        .WithMany("SolutionFiles")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("solution");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BaseConn.Domain.models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BaseConn.Domain.models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseConn.Domain.models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BaseConn.Domain.models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseConn.Domain.models.ApplicationUser", b =>
                {
                    b.Navigation("FounderProblems");

                    b.Navigation("Notes");

                    b.Navigation("Problems");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Note", b =>
                {
                    b.Navigation("NoteFiles");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Problem", b =>
                {
                    b.Navigation("ProblemFiles");

                    b.Navigation("solutions");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Service", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BaseConn.Domain.models.Solution", b =>
                {
                    b.Navigation("SolutionFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
